sylius_grid:
    grids:
        app_admin_color:
            driver:
                options:
                    class: "%app.model.productcolor.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
