sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                product_color:
                    template: 'Shop/ProductColor.html.twig'
                    priority: 29
